amcl:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0

controller_server:
  ros__parameters:
    expected_control_frequency: 10.0

bt_navigator:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

local_costmap:
  ros__parameters:
    footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
    resolution: 0.05

global_costmap:
  ros__parameters:
    resolution: 0.05
