slam_toolbox:
  ros__parameters:
    use_sim_time: false           # Set to true if you're using simulation like Gazebo or rosbag
    slam_mode: true               # Enable SLAM (vs localization mode)
    map_file_name: "map"          # File to save the map (via map_saver)
    resolution: 0.05              # Grid resolution in meters
    publish_period_sec: 1.0       # How often to publish map
    use_scan_matching: true
    mode: "mapping"               # Other options: "localization"
    map_start_pose: [0.0, 0.0, 0.0]
    transform_timeout: 0.2
    tf_buffer_duration: 10.0
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    max_submaps_to_keep: 10
    scan_topic: /scan
    odom_frame: odom
    map_frame: map
    base_frame: base_link
