slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping                     # online mapping mode
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5

    map_update_interval: 2.0
    transform_publish_period: 0.05

    # Solver config
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    use_scan_matching: true
    use_slam_mode: true

    publish_map: true
    publish_pose: true
    publish_to_tf: true
